project:
  type: website
  resources: 
    - "*.pdf"
    - "verification-follow_it-FAZdtWh8AR1plJVdm63V.html"
    
website:
  title: "Yangzhuoran Fin Yang"
  favicon: img/icon-192.png
  site-url: "https://yangzhuoranyang.com"
  google-analytics: G-W89QFE55QW
  page-footer: 
    background: "#3F555D"
    left: "&copy; 2017-[]{#current-year}, Yangzhuoran Yang"
    right:
      - text: Subscribe
        href: /subscribe
      - icon: rss
        href: posts/index.xml
  navbar:
    pinned: true
    background: "#3F555D"
    right:
      - href: posts/index.qmd
        text: Blog
      - href: publication/index.qmd
        text: Publications
      - href: software/index.md
        text: Software
      - href: talk/index.qmd
        text: Talks
      - href: teaching/index.md
        text: Teaching
      - href: https://github.com/FinYang/CV/raw/master/AwesomeCV/YangzhuoranYang_CV.pdf
        text: CV
      # - href: contact/index.qmd
      #   text: Contact
  announcement: 
    icon: info-circle
    dismissable: true
    content: "I just started a blog! Check out my first post: [30 isn't a reliable cutoff for a \"large\" sample](/posts/n30)."
    type: success
    position: below-navbar

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    backgroundcolor: "#EDE3DA"
    include-after-body:
      - text: |
          <script>
            document.getElementById('current-year').textContent = new Date().getFullYear();
          </script>
    
execute: 
  freeze: auto

date-format: "D MMM YYYY"
